%YAML:1.0

#File paths
VideoPath: "/home/alex/mser/datasets/through_the_cracks_jing.mov" #input video
BALPath: "/home/alex/mser/datasets/fpv_bal_280_nf2.txt" #BAL file with visual odometry results
#CSVPath: "/home/alex/mser/datasets/mserMeasurements.csv" #CSV file with MSER track results
VertexShaderPath: "/home/alex/mser/mser_3d/TransformVertexShaderTutorial.vertexshader"
FragmentShaderPath: "/home/alex/mser/mser_3d/TextureFragmentShader.fragmentshader"
CSVPath: "/home/alex/mser/mser_2d/tempManualMserMeasurements.csv" #CSV file with MSER track results
#CSVPath: "/home/alex/mser/datasets/firstManualMeasurementGroup.csv" #CSV file with MSER track results
#CSVPath: "/home/alex/mser/datasets/bothManualMeasurementGroups.csv" #CSV file with MSER track results
#CSVPath: "/home/alex/mser/datasets/track9.csv" #CSV file with MSER track results
#CSVPath: "/home/alex/mser/datasets/first29Tracks.csv" #CSV file with MSER track results
#CSVPath: "/home/alex/mser/datasets/first14Tracks.csv" #CSV file with MSER track results

#Camera parameters. Assuming 720p GoPro
Camera.fx: 857.483
Camera.fy: 876.718
Camera.s: 0.1
Camera.cx: 640  #1280/2
Camera.cy: 360  #720/2

#OpenCV MSER tuning parameters 
MSER.Delta: 10
MSER.MinArea: 1000
MSER.MaxArea: 10000
MSER.MaxVariation: 0.2
MSER.MinDiversity: 0.2
MSER.MaxEvolution: 200 #
MSER.AreaThreshold: 1.01 #
MSER.MinMargin: 0.003 #
MSER.EdgeBlurSize: 50 #

#Visualization settings:
Vis.ShowRays: 1 #(BOOLEAN) Show lines from camera through measurement centroid (USES A LOT OF VRAM)
ImagePath: "/home/alex/mser/datasets/RenderedImages/"
